# Use Ubuntu 20.04 & ros1 neotic as the base image
FROM ros:noetic-ros-base

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    git \
    wget \
    vim \
    libopencv-dev \
    pkg-config \
    libeigen3-dev \
    libboost-all-dev \
    python3-dev python3-pip python3-scipy python3-matplotlib \
    && apt-get clean

RUN apt-get install -y \
    x11-apps \
    libgtk2.0-dev \
    libcanberra-gtk-module \
    libcanberra-gtk3-module
    
RUN apt-get update && apt-get install -y \
  ros-noetic-cv-bridge \
  ros-noetic-image-transport \
  ros-noetic-image-transport-plugins \
  ros-noetic-pcl-ros \
  ros-noetic-pcl-conversions \
  ros-noetic-image-geometry \
  ros-noetic-camera-info-manager \
  ros-noetic-rviz \
  ros-noetic-eigen-conversions \
  ros-noetic-tf-conversions \
  python3-catkin-tools \
  ros-noetic-vision-msgs \
  rsync

RUN apt-get update && apt-get install -y \
    ros-noetic-rqt-common-plugins \
    ros-noetic-rqt-image-view \
    ros-noetic-rqt-graph \
    ros-noetic-rqt-topic

RUN git clone https://github.com/luxonis/depthai-core.git && \
    cd depthai-core && \
    git checkout v2_stable && \
    git submodule update --init --recursive && \
    cmake -S. -Bbuild -D'BUILD_SHARED_LIBS=ON' -D'CMAKE_INSTALL_PREFIX=/opt/depthai-install' && \
    cmake --build build --target install -j4

    
WORKDIR /workspace

CMD ["/bin/bash"]